// Every string the user reads, verbatim from ai/PRODUCT-BRIEF.md section 5b.
export const copy = {
  appName: 'Kobo',
  welcomeTitle: 'Get paid in digital dollars',
  welcomeBody: 'Price in naira. Your customer pays in USDC. You see it arrive in seconds.',
  connect: 'Connect wallet',
  viewOnly: 'View only',
  connecting: 'Connecting…',
  connectError: "Couldn't connect. Open your wallet app and try again.",
  noWallet: 'No Solana wallet found on this phone. Install Phantom or Solflare, then come back.',
  viewOnlyBanner: 'View only: connect a wallet to send rewards and refunds',
  viewOnlyStaff: 'View only suits a staff phone: no wallet on it, and every payment still lands in your wallet. Rewards and refunds need your wallet connected.',
  setupTitle: 'Your shop',
  shopNameLabel: 'Shop name',
  shopNamePlaceholder: 'e.g. Mama Nkechi Provisions',
  shopNameError: 'Give your shop a name (2 to 40 letters).',
  acceptLabel: 'Accept',
  coinsOffError: 'Turn on at least one coin.',
  rewardLabel: 'Reward Seeker customers',
  rewardHelp: 'Paid in SKR when you close the day. One reward per Seeker phone per day.',
  rateAdjustLabel: 'Rate adjustment',
  save: 'Save',
  tillRateLine: (rate: string, hhmm: string) => `₦${rate} per $1 · updated ${hhmm}`,
  tillRateLoading: "Getting today's rate…",
  tillRateOffline: (hhmm: string) => `Using rate from ${hhmm} (offline)`,
  tillRateManual: "Type today's rate (₦ per $1)",
  tillRateDisagree: (rate: string) => `Rate sources disagree. Using ₦${rate}. Tap to change.`,
  charge: 'Charge',
  waitingLine: 'Waiting for payment…',
  waitingScanHint: 'Scan with your Solana wallet',
  waitingLong: (hhmm: string) => `Still waiting. The rate is locked from ${hhmm}.`,
  waitingOffline: "No internet. The payment will still arrive; Kobo will confirm it when you're back online.",
  cancel: 'Cancel',
  paidTitle: (naira: string) => `Paid ₦${naira}`,
  paidFrom: (coins: string, coin: string, payer: string) => `${coins} ${coin} from ${payer}`,
  paidSeekerBadge: 'Seeker customer · reward at close',
  paidByAmountNote: 'Paid (matched by amount)',
  uniqueAmountNote: 'A few extra digits keep this amount unique, so Kobo can tell this sale apart.',
  sameAmountNote: 'Two sales have the same amount. Waiting for the exact payment.',
  shareReceipt: 'Share receipt',
  sharePayLink: 'Send payment link',
  printReceipt: 'Print',
  printPaid: 'Paid',
  printOverpaid: 'Paid (overpaid)',
  printProof: 'Scan to check this payment on Solana',
  printFooter: 'Paid to the shop\'s own wallet. Kobo never holds the money.',
  alertChannel: 'Payments',
  alertPaid: (naira: string) => `Paid ₦${naira}`,
  alertUnderpaid: (naira: string) => `Underpaid ₦${naira} sale`,
  alertBody: (coins: string, coin: string, from: string, shop: string) => `${coins} ${coin}${from ? ` from ${from}` : ''} · ${shop}`,
  addItem: '+ Item',
  itemsLabel: (n: number) => `${n} items`,
  receiptItems: 'Items',
  linkValid: (hhmm: string) => `Payment link sent, valid until ${hhmm}`,
  linkExpired: (hhmm: string) => `Payment link expired at ${hhmm}. Kobo still records a payment that arrives.`,
  payLinkText: (shop: string, naira: string, coins: string, coin: string, hhmm: string, url: string) =>
    `${shop}: please pay ₦${naira}, that is ${coins} ${coin} on Solana (rate locked at ${hhmm}). Pay here: ${url}`,
  newSale: 'New sale',
  receiptText: (shop: string, coins: string, coin: string, naira: string, hhmm: string, date: string, url: string) =>
    `${shop}: received ${coins} ${coin} (₦${naira}) at ${hhmm}, ${date}. Proof: ${url}`,
  underpaidTitle: (short: string) => `Underpaid: ₦${short} short`,
  underpaidBody: (got: string, want: string, coin: string) => `Received ${got} of ${want} ${coin}`,
  chargeRest: 'Charge the rest',
  acceptAsIs: 'Accept as is',
  todayTotals: (naira: string, usd: string) => `₦${naira} today · $${usd}`,
  yourDollars: (usd: string) => `Your dollars: $${usd}`,
  todayEmpty: 'No sales yet today. Tap Till to take your first payment.',
  balanceOffline: 'Balance unavailable offline',
  closeDay: 'Close the day',
  refund: 'Refund',
  refundOpening: 'Opening your wallet…',
  refundFailed: 'Refund not sent. Nothing left your wallet.',
  refundLowBalance: (coin: string, coins: string) => `Not enough ${coin} in the shop wallet to refund ${coins}.`,
  refundDone: (coins: string, coin: string, payer: string) => `Refunded ${coins} ${coin} to ${payer}`,
  closeSummary: (n: number, naira: string) => `Today: ${n} sales · ₦${naira}`,
  closeRewards: (k: number, pct: string, usd: string, skr: string) =>
    `Seeker rewards: ${k} customers · ${pct}% · $${usd} → about ${skr} SKR`,
  noSkrAccount: 'No SKR account',
  closeNone: 'No Seeker customers today. Nothing to send.',
  sendRewards: 'Send rewards',
  skipRewards: 'Skip rewards today',
  quoteLoading: 'Getting the best SKR price…',
  approveLoading: 'Approve in your wallet…',
  quoteFailed: "Couldn't get an SKR price. Try again in a minute.",
  rewardsFailed: 'Rewards not sent. Nothing left your wallet.',
  rewardsLowUsdc: (usd: string) => `You need $${usd} in USDC to send today's rewards.`,
  rewardMemo: (shop: string) => `Kobo reward from ${shop}`,
  shopQrTitle: 'Your shop QR',
  saveImage: 'Save image',
  saveFailed: "Couldn't save the image. Check storage permission.",
  cashoutBody: 'Kobo never holds or converts your money. To get naira, send dollars to a licensed exchange:',
  cashoutBusha: 'Open Busha',
  cashoutQuidax: 'Open Quidax',
  networkFast: 'Fast connection',
  networkPublic: 'Using public network connection',
  disconnectConfirm: 'Disconnect? Your sales history stays on this phone.',
  done: 'Done',
  sent: 'Sent',
  disconnect: 'Disconnect',
  cashout: 'Cash out',
  copyAddress: 'Copy address',
  viewOnSolscan: 'View on Solscan',
  addressPlaceholder: 'Solana address',
  rewardSent: 'SKR reward sent',
  rewardSkipped: 'No reward today',
  refundConfirm: (coins: string, coin: string, address: string) => `Refund ${coins} ${coin} to this address?\n${address}`,
  refundHeldBack: (reward: string, coin: string) => `${reward} ${coin} Seeker reward already paid is kept back.`,
  refundAlready: 'Already refunded. Kobo found the refund on Solana.',
  testBanner: 'Test network: not real money',
  chainChecked: (time: string) => `Checked ${time}`,
  rateLocked: (rate: string, hhmm: string) => `Rate ₦${rate} per $1, locked at ${hhmm}`,
  receiptReceived: 'Received',
  receiptFrom: 'From',
  receiptTime: 'Time',
  receiptRate: 'Rate',
  receiptExpected: 'Expected',
  receiptCoin: 'Coin',
  receiptReward: 'Reward',
  example: 'Example',
  todayRewardsOwed: (k: number) => `Seeker rewards to send at close: ${k}`,
} as const
